[tool.poetry]
name = "colortradutor"
version = "0.1.0"
description = "ColorTradutor - Tradução visual com destaque por cores."
authors = ["Joao Carlos - PC Online <joao.carlos.dev.log@gmail.com>"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
deep-translator = "^1.11.4"
customtkinter = "^5.2.0"
pillow = ">=10.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
